### PR TITLE
tests: adds test function for IdnaTestV2.json

### PR DESCRIPTION
**Pull request by miguelteixeiraa**
ref: https://github.com/ada-url/ada/issues/222

The good news is that almost all tests cases are passing.

### CODE REVIEW

**Comment by lemire** [comment]
@miguelteixeiraa Would you add it to https://github.com/ada-url/idna ?

We eventually want to rely on ada-url/idna for ada.

**Comment by miguelteixeiraa** [comment]
> @miguelteixeiraa Would you add it to https://github.com/ada-url/idna ?
> 
> We eventually want to rely on ada-url/idna for ada.

Done!

**Comment by lemire** [comment]
@miguelteixeiraa Why did you close it here? In my view, it belongs at both places. Your work here was good and relevant. Of course, here you were testing our ICU-based implementation, but no matter. My understanding is that your tests ought to pass everywhere (or, else, we need to figure something out).

**Comment by anonrig** [comment]
There is 1 test case we are failing at the moment.

```
FAIL: 
  Returned: xn--8-qfa.xn---?-261a
  Test case: {
    "comment": "P1; V6; V3 (ignored)",
    "input": "8\u00df.\udb40\udd10-?\u2d0f",
    "output": null
  }
```

**Comment by anonrig** [comment]
We moved is_forbidden_domain_code_point check to outside of `to_ascii` method. I assume this is why it's breaking this pull request. We just need to add the following lines to wpt_tests with a `TODO` to fix this when we get rid of ICU.

```c++
if (output.has_value()) {
  if (std::any_of(output.value().begin(), output.value().end(), ada::unicode::is_forbidden_domain_code_point)) {
    output = std::nullopt;
  }
}
```

**Comment by miguelteixeiraa** [comment]
Is it okay to remove the **ada_really_inline constexpr** from **is_forbidden_domain_code_point**? I'm getting linkage problems.

**Comment by lemire** [comment]
@miguelteixeiraa  This will need to be updated because we did major surgery on the code.

**Comment by lemire** [comment]
Let me see if I can integrate the code in the other PR.

**Comment by lemire** [comment]
I am going to push the content of this PR into https://github.com/ada-url/ada/pull/216 

It will be less trouble for everyone.

You may close this PR.

**Pull request closed without merging**
