### PR TITLE
fix: handle base url authority setter properly

### PR DESCRIPTION
**Pull request by anonrig**

### CODE REVIEW

**Review by lemire — COMMENTED** [review]
Is creating a new temporary string necessary? I have some other fixes that may serve a similar purpose in...

https://github.com/ada-url/ada/pull/295

I do not use temporary strings... 

I would try as hard as possible to avoid creating temporary strings.

**Comment by anonrig** [comment]
> Is creating a new temporary string necessary? I have some other fixes that may serve a similar purpose in...

It's not necessary, actually quite easy, but I wanted to make sure it works first. I'll definitely get rid of the `get_authority_buffer()` or just pass a `std::string_view` to set_authority function before removing the work in progress mention.

**Comment by anonrig** [comment]
@lemire this is ready to get merged, please review

**Comment by lemire** [comment]
Merging.

**Pull request merged**
