### PR TITLE
separate fuzzers into different files

### PR DESCRIPTION
**Pull request by CarlosEduR**

### CODE REVIEW

**Comment by anonrig** [comment]
Can you also update build.sh file?

**Comment by CarlosEduR** [comment]
> Can you also update build.sh file?

Sure, I have to run linter as well

**Comment by CarlosEduR** [comment]
@anonrig we should be able to see the results here, right? https://storage.googleapis.com/oss-fuzz-introspector/ada-url/inspector-report/20240513/fuzz_report.html

Just wanted to confirm it is configured correctly.

**Comment by anonrig** [comment]
> @anonrig we should be able to see the results here, right? https://storage.googleapis.com/oss-fuzz-introspector/ada-url/inspector-report/20240513/fuzz_report.html


@CarlosEduR Yes but they run it on a cronjob. The GitHub workflow is merely for local development and does not cover the whole fuzzer.

Basically, oss-fuzz runs a docker file (implemented in https://github.com/google/oss-fuzz/tree/master/projects/ada-url) which executes `build.sh` in this repository.

**Comment by anonrig** [comment]
@CarlosEduR Can you also disable memory sanitizer in a different pull-request if you don't mind?

**Comment by CarlosEduR** [comment]
> @CarlosEduR Can you also disable memory sanitizer in a different pull-request if you don't mind?

sure, @CarlosEduR! From the cifuzz.yml, right?

**Comment by CarlosEduR** [comment]
@anonrig 
image

**Comment by anonrig** [comment]
@CarlosEduR they are not blocked. they just test a specific portion of the codebase ~0.1%. but this is good progress!

**Pull request merged**
