### PR TITLE
Let us disable, by default, most competitors.

### PR DESCRIPTION
**Pull request by lemire**
This will speed up tremendously our builds.

### CODE REVIEW

**Review by anonrig — COMMENTED** [review]
We should also update the GitHub workflows not to install competition packages.

**Comment by lemire** [comment]
> We should also update the GitHub workflows not to install competition packages.

By default, they won't if you merge this PR.

**Comment by anonrig** [comment]
We're installing 

- CURL in here: https://github.com/ada-url/ada/blob/main/.github/workflows/ubuntu.yml#L27
- Boost in here: https://github.com/ada-url/ada/blob/main/.github/workflows/ubuntu.yml#L29

**Comment by lemire** [comment]
@anonrig I think I addressed your concerns, merging.

**Pull request merged**
