### PR TITLE
perf: improve is_ipv4_number_valid

### PR DESCRIPTION
**Pull request by anonrig**
Before
```
BasicBench_AdaURL            7374 ns         7341 ns        94908 time/byte=9.64605ns
```

After
```
BasicBench_AdaURL            7199 ns         7189 ns        97386 time/byte=9.44628ns
```

### CODE REVIEW

**Comment by lemire** [comment]
Is this a real optimization? I do not see anything in the diff that might explain a performance boost. Note that the benchmark so we can't do a direct comparison.

(The PR itself is fine, I just do not expect it to improve the performance.)

**Comment by anonrig** [comment]
@lemire Reducing the number of branches in the checkers.cpp resulted in 100+ns improvement. There were some unnessary checks.

**Comment by anonrig** [comment]
Let’s merge if there is no objections @lemire

**Comment by lemire** [comment]
> Reducing the number of branches in the checkers.cpp resulted in 100+ns improvement. There were some unnessary checks.

Ah. Yes. I stand corrected. I see the optimization now.

**Pull request merged**
