### PR TITLE
Update web platform tests

### PR DESCRIPTION
**Pull request by anonrig**
This is an automated pull request for updating the WPT

### CODE REVIEW

**Review by lemire — COMMENTED** [review]
Is this correct? There is a reference to a README file... and it seems to move all the about:blank to null.

If it is correct, then please merge, but it looks a bit strange.

**Comment by anonrig** [comment]
> Is this correct? There is a reference to a README file... and it seems to move all the about:blank to null.
> 
> 
> 
> If it is correct, then please merge, but it looks a bit strange.

@lemire This is the relevant change: https://github.com/web-platform-tests/wpt/commit/6d461b4ddb2f1b8d226ca6ae92e14bbd464731a5. I will take a look at it in depth.

**Review by lemire — APPROVED** [review]

**Comment by lemire** [comment]
I think you are concerned about these lines, right? 

Capture d’écran, le 2023-03-29 à 21 44 14

**Comment by lemire** [comment]
I expect that the null bases are not much of a problem... we can do `if(element["base"].is_null()) {`, so that's fine.

**Comment by anonrig** [comment]
I'm working on updating the web platform test script to work with this change. I'll commit shortly...

**Comment by anonrig** [comment]
I'm closing this to trigger a new branch for the script.

**Pull request closed without merging**
