### PR TITLE
Infinite Trailing dots in IPv4 addrs at the end

### PR DESCRIPTION
**Pull request by the-moisrex**
Even though WHATWG only mentions the last empty octet to be a warning (https://url.spec.whatwg.org/#ipv4-empty-part), but I don't think something like "http://127.0.0.1.../" should be marked as Too Many Parts (https://url.spec.whatwg.org/#ipv4-too-many-parts).

Browsers' URL Parsers that I tested do ignore the last dot characters as well.

I'm not sure if this needs to be merged or not, but if I were writing WHATWG I either wouldn't have let the last dot be valid at all, or multiple dots would be okay too; I also wouldn't allow hex/octal IPv4 addresses either, so what do I know!!

Thanks.

### CODE REVIEW

**Comment by the-moisrex** [comment]
I broke something it seems like it. (http://foo.09..)

**Comment by the-moisrex** [comment]
Well, technically, `http://foo.09..` should be an invalid host if we ignore trailer empty octets of an ipv4, thus the `http://foo.09..` url, must be a either a valid IPv4, or it's invalid completely and cannot be a normal "host".

**Comment by lemire** [comment]
>  I don't think something like "http://127.0.0.1.../" should be marked as Too Many Parts

It is possible that we misread or misinterpret the WHATWG URL specification with respect to IPv4. My current reading of the specification is that `127.0.0.1...` is indeed to be rejected. There is a special case where we discard the trailing dot, producing `127.0.0.1..`, so have the following parts `127`, `0`, `0`, `1`, `` (empty string).

Can you explain your objection in terms of the WHATWG URL specification itself? We, very deliberately, do not have opinions on what a URL should be. We just interpret the standard the best we can, and we try to provide a 100% conformant implementation.


## General algorithm:
Capture d’écran, le 2023-12-26 à 16 18 45


## IPv4 number parser:
Capture d’écran, le 2023-12-26 à 16 18 54


> Well, technically, http://foo.09.. should be an invalid host if we ignore trailer empty octets of an ipv4, thus the http://foo.09.. url, must be a either a valid IPv4, or it's invalid completely and cannot be a normal "host".

[This test is part of the WPT WHATWG URL testing set](https://github.com/ada-url/ada/blob/d6bca38600a0b6a960e277ad23eeb4c280345196/tests/wpt/urltestdata.json#L8790). It is possible that WPT misinterpreted the standard or produced a bad test. If think so, can you report the issue at WPT? The ada library is the wrong place to debate these issues.


> I also wouldn't allow hex/octal IPv4 addresses either, so what do I know!!

It is prescribed by the WHAT URL standard, please see my screenshot above. If you think that the WHATWG URL standard is wrong, you should take it up with them. The ada library is the wrong place to debate the content of the standard.

**Comment by the-moisrex** [comment]
I see. Thanks anyway.

**Pull request closed without merging**
